// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:browny_applications_new/core/data/cache/hive/app_hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CustomerProfileDataAdapter());
    registerAdapter(LoginCustomerDataAdapter());
    registerAdapter(StoreSearchHistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CustomerProfileDataAdapter());
    registerAdapter(LoginCustomerDataAdapter());
    registerAdapter(StoreSearchHistoryAdapter());
  }
}
