// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdMEX1RFkOOvjedCUFz5Jt2Rh8JmZG0xA',
    appId: '1:261060252828:web:d9fe5399675d975fcb0959',
    messagingSenderId: '261060252828',
    projectId: 'brownyapplication',
    authDomain: 'brownyapplication.firebaseapp.com',
    storageBucket: 'brownyapplication.firebasestorage.app',
    measurementId: 'G-GN5177GTSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54Z7g9HqyTeV8iLgql3UzvKiN6lVX5X4',
    appId: '1:261060252828:android:9d9c84bf697e5bb0cb0959',
    messagingSenderId: '261060252828',
    projectId: 'brownyapplication',
    storageBucket: 'brownyapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHUkBob33OxloJYxtn4cIrgQf2VzkaiM',
    appId: '1:261060252828:ios:9870cc33ef706c99cb0959',
    messagingSenderId: '261060252828',
    projectId: 'brownyapplication',
    storageBucket: 'brownyapplication.firebasestorage.app',
    androidClientId: '261060252828-cja0m2dsg7d8ubumfsk809uhfge7bgrk.apps.googleusercontent.com',
    iosClientId: '261060252828-8fonmpfeeqkqhb420dui4q0afo7dsqlq.apps.googleusercontent.com',
    iosBundleId: 'com.brownywash.brownyapplications',
  );

}